spring.application.name=astracloud2
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

## baza danych
spring.datasource.url=jdbc:postgresql://1.1.1.1:5134/astracloud?sslmode=require
spring.datasource.username=spring_user
spring.datasource.password=haslo

# schemat tworzymy skryptem. 'validate' sprawdza czy istnieją wymagane tabele.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
